version: "3.8"

services:
  python-app-ai:
    build:
      context: .containers/tools
      dockerfile: Dockerfile
    hostname: tree
    image: tree-app:latest
    container_name: python-tree-app
    restart: no
    working_dir: /app
    command: sleep infinity
    environment:
      # Zaman damgalarının doğru olduğu timezone
      - TZ=Europe/Istanbul
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      # - SDL_AUDIODRIVER: dummy
    volumes:
      - ./:/app:cached
      - /tmp/.X11-unix:/tmp/.X11-unix           # GUI erişimi için
      - /run/user/1000/pulse:/run/user/1000/pulse
    user: "${UID}:${GID}"
    network_mode: host  # DISPLAY için gerekli (Linux'ta)
    devices:
      - /dev/snd  # (isteğe bağlı, ses gerekiyorsa)
      - /dev/dri  # (isteğe bağlı, grafik hızlandırma gerekiyorsa)
    stdin_open: true
    tty: true

    # Eğer container’ı DEBUG seviyesinde veya INFO/DEBUG ayarlı çalıştırmak istersen:
    # command: ["python", "-u", "logging_app.py", "-vv"]
  
